name: Stage 1
trigger: none

schedules:
  - cron: "0 15 * * Fri"
    displayName: Friday 8am PT Trigger
    branches:
      include:
        - master
    always: true

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  displayName: 'Checkout Self'
  persistCredentials: true
- powershell: ./PrintHelloWorld.ps1
  displayName: 'Print Hello World'





jobs:
- job: Build_and_Test
  displayName: Build and Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo "Building the project..."
      dotnet build MyProject.csproj
    displayName: 'Build'
  - task: PythonScript@0
    inputs:
      command: 'run'
      projects: 'main.py'
    displayName: 'Python script'

- job: Deploy_to_Staging
  displayName: Deploy to Staging
  dependsOn: Build_and_Test
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: JavaApp@1
    inputs:
      command: 'run'
      projects: 'main.py'
    displayName: 'Python script'

- job: Deploy_to_Production
  displayName: Deploy to Production
  dependsOn: Build_and_Test
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PythonScript@0
    inputs:
      command: 'run'
      projects: 'main.py'
    displayName: 'Python script'
  - publish: "filepath"
    artifact: "testA_Artifact"
    displayName: "Publish Artifact"
