trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/**
  tags:
    include:
      - v*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Building with Node.js"
        npm install
        npm run build
      displayName: 'npm install and build'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Use Python 3.x'
    - script: |
        echo "Building with Python"
        pip install -r requirements.txt
        python build.py
      displayName: 'pip install and build'
